# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [ ]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [7]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [9]:
a

array([ 0.,  0.,  0.])

In [10]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
c

array([[[4, 3, 3, 9],
        [2, 9, 9, 6],
        [1, 4, 8, 2]],

       [[5, 5, 3, 1],
        [8, 8, 9, 7],
        [4, 9, 5, 2]]])

In [12]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[4, 3, 3, 9],
         [2, 9, 9, 6],
         [1, 4, 8, 2]],
 
        [[5, 5, 3, 1],
         [8, 8, 9, 7],
         [4, 9, 5, 2]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [13]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [14]:
c = a-b
c

array([20, 29, 38, 47])

In [15]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [16]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [17]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
a[2:5]

array([ 4,  9, 16])

In [19]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [20]:
b = np.random.randint(1,100,(4,4))

In [21]:
b

array([[76, 51, 57, 83],
       [98, 10, 69, 23],
       [10,  6, 91, 10],
       [75, 36, 50, 69]])

In [22]:
# Guess the output
print(b[2,3])
print(b[0,0])


10
76


In [23]:
b[0:3,1],b[:,1]

(array([51, 10,  6]), array([51, 10,  6, 36]))

In [24]:
b[1:3,:]

array([[98, 10, 69, 23],
       [10,  6, 91, 10]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [27]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [28]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418
2014-01-06 -0.181697  0.985749  1.281486  3.539555

In [29]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [30]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [31]:
df.head()

A         B         C         D
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418

In [32]:
df.tail()

A         B         C         D
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418
2014-01-06 -0.181697  0.985749  1.281486  3.539555

In [33]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [44]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.281065  0.561618  0.236156  1.081203
std    0.701126  0.603311  0.929742  1.442224
min   -1.068364 -0.226227 -0.847003 -0.431202
25%   -0.786615  0.050619 -0.559787  0.270545
50%   -0.348918  0.759889  0.254614  0.603284
75%    0.040392  1.046917  1.042015  1.660318
max    0.842160  1.119371  1.281486  3.539555

In [35]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418
2014-01-06 -0.181697  0.985749  1.281486  3.539555

### Selection

In [36]:
df[['A','B']]

A         B
2014-01-01  0.842160 -0.110518
2014-01-02 -0.516139  1.067306
2014-01-03 -1.068364  0.534029
2014-01-04 -0.876773  1.119371
2014-01-05  0.114422 -0.226227
2014-01-06 -0.181697  0.985749

In [37]:
df[0:3]

A         B         C         D
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151

In [38]:
# By label
df.loc[dates[0]]

A    0.842160
B   -0.110518
C   -0.029903
D   -0.431202
Name: 2014-01-01 00:00:00, dtype: float64

In [39]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.842160 -0.110518
2014-01-02 -0.516139  1.067306
2014-01-03 -1.068364  0.534029
2014-01-04 -0.876773  1.119371
2014-01-05  0.114422 -0.226227
2014-01-06 -0.181697  0.985749

In [40]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  1.067306
2014-01-03  0.534029
2014-01-04  1.119371

In [41]:
# Fast access to scalar
df.at[dates[1],'B']

1.0673058550639876

In [42]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418
2014-01-06 -0.181697  0.985749  1.281486  3.539555

### Boolean Indexing

In [43]:
    df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-02 -0.516139  1.067306  0.539130  0.194343
2014-01-03 -1.068364  0.534029  1.209643  0.499151
2014-01-04 -0.876773  1.119371 -0.736416  1.977952
2014-01-06 -0.181697  0.985749  1.281486  3.539555

### Setting

In [45]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [46]:
df_posA

A         B         C         D
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202
2014-01-02  0.516139 -1.067306 -0.539130 -0.194343
2014-01-03  1.068364 -0.534029 -1.209643 -0.499151
2014-01-04  0.876773 -1.119371  0.736416 -1.977952
2014-01-05  0.114422 -0.226227 -0.847003  0.707418
2014-01-06  0.181697 -0.985749 -1.281486 -3.539555

In [47]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [48]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [49]:
df['F'] = s1

In [50]:
df

A         B         C         D    F
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202  NaN
2014-01-02 -0.516139  1.067306  0.539130  0.194343  1.0
2014-01-03 -1.068364  0.534029  1.209643  0.499151  2.0
2014-01-04 -0.876773  1.119371 -0.736416  1.977952  3.0
2014-01-05  0.114422 -0.226227 -0.847003  0.707418  4.0
2014-01-06 -0.181697  0.985749  1.281486  3.539555  5.0

### Missing Data

In [51]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [52]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [53]:
df1

A         B         C         D    F    E
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202  NaN  1.0
2014-01-02 -0.516139  1.067306  0.539130  0.194343  1.0  1.0
2014-01-03 -1.068364  0.534029  1.209643  0.499151  2.0  NaN
2014-01-04 -0.876773  1.119371 -0.736416  1.977952  3.0  NaN

In [54]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [55]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.281065  0.561618  0.236156  1.081203  3.000000
std    0.701126  0.603311  0.929742  1.442224  1.581139
min   -1.068364 -0.226227 -0.847003 -0.431202  1.000000
25%   -0.786615  0.050619 -0.559787  0.270545  2.000000
50%   -0.348918  0.759889  0.254614  0.603284  3.000000
75%    0.040392  1.046917  1.042015  1.660318  4.000000
max    0.842160  1.119371  1.281486  3.539555  5.000000

In [56]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.281065
 B    0.561618
 C    0.236156
 D    1.081203
 F    3.000000
 dtype: float64, 2014-01-01    0.067634
 2014-01-02    0.456928
 2014-01-03    0.634892
 2014-01-04    0.896827
 2014-01-05    0.749722
 2014-01-06    2.125019
 Freq: D, dtype: float64)

### Applying functions

In [57]:
df

A         B         C         D    F
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202  NaN
2014-01-02 -0.516139  1.067306  0.539130  0.194343  1.0
2014-01-03 -1.068364  0.534029  1.209643  0.499151  2.0
2014-01-04 -0.876773  1.119371 -0.736416  1.977952  3.0
2014-01-05  0.114422 -0.226227 -0.847003  0.707418  4.0
2014-01-06 -0.181697  0.985749  1.281486  3.539555  5.0

In [58]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.842160 -0.110518 -0.029903 -0.431202   NaN
2014-01-02  0.326020  0.956788  0.509227 -0.236859   1.0
2014-01-03 -0.742344  1.490817  1.718870  0.262292   3.0
2014-01-04 -1.619117  2.610188  0.982454  2.240244   6.0
2014-01-05 -1.504695  2.383961  0.135451  2.947661  10.0
2014-01-06 -1.686392  3.369710  1.416937  6.487217  15.0

In [59]:
df.apply(lambda x: x.max() - x.min())

A    1.910524
B    1.345597
C    2.128490
D    3.970758
F    4.000000
dtype: float64

In [60]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [61]:
np.random.randn(10,4)

array([[-0.69292191,  0.21050197, -0.67016068, -0.58124092],
       [ 0.51592011,  0.31567215,  0.29693278,  0.65355245],
       [ 1.34837413, -2.08150672,  0.31497033,  0.76551556],
       [-0.69288692, -0.71553619, -2.61633447, -0.34003259],
       [-0.54465345,  0.32072414, -0.44271253, -0.39611843],
       [ 0.22331604, -0.70230322, -0.73849804,  1.09558063],
       [-0.45232971, -1.50246046,  2.195684  , -0.3261482 ],
       [-0.42163538, -2.80423795,  0.55055517,  0.09380136],
       [ 1.43472524,  1.34960309, -1.85806829, -1.4749862 ],
       [-0.62054315, -1.9378066 ,  0.89431327,  0.2925394 ]])

In [62]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.216823 -1.085390 -0.981395  0.234757
1  0.045329  0.075906 -0.721422 -1.211356
2  0.574224  0.672144 -1.010159 -1.503583
3 -0.063197  0.003029  0.494699  0.664745
4 -2.152184  0.665712 -0.514321 -0.371065
5  0.016120  2.214071 -0.172869 -2.811237
6  1.770209 -0.621106 -1.382563  0.924840
7  0.823469 -0.815172  0.283333  1.072061
8  0.674455 -0.022174 -2.353393  1.240661
9 -0.006946 -1.963682 -0.887949  1.800675

In [63]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -0.216823 -1.085390 -0.981395  0.234757
 1  0.045329  0.075906 -0.721422 -1.211356
 2  0.574224  0.672144 -1.010159 -1.503583,
           0         1         2         3
 3 -0.063197  0.003029  0.494699  0.664745
 4 -2.152184  0.665712 -0.514321 -0.371065
 5  0.016120  2.214071 -0.172869 -2.811237
 6  1.770209 -0.621106 -1.382563  0.924840,
           0         1         2         3
 7  0.823469 -0.815172  0.283333  1.072061
 8  0.674455 -0.022174 -2.353393  1.240661
 9 -0.006946 -1.963682 -0.887949  1.800675]

In [64]:
pd.concat(pieces)

0         1         2         3
0 -0.216823 -1.085390 -0.981395  0.234757
1  0.045329  0.075906 -0.721422 -1.211356
2  0.574224  0.672144 -1.010159 -1.503583
3 -0.063197  0.003029  0.494699  0.664745
4 -2.152184  0.665712 -0.514321 -0.371065
5  0.016120  2.214071 -0.172869 -2.811237
6  1.770209 -0.621106 -1.382563  0.924840
7  0.823469 -0.815172  0.283333  1.072061
8  0.674455 -0.022174 -2.353393  1.240661
9 -0.006946 -1.963682 -0.887949  1.800675

In [65]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.216823 -1.085390 -0.981395  0.234757
1  0.045329  0.075906 -0.721422 -1.211356
2  0.574224  0.672144 -1.010159 -1.503583
3 -0.063197  0.003029  0.494699  0.664745
4 -2.152184  0.665712 -0.514321 -0.371065
5  0.016120  2.214071 -0.172869 -2.811237
6  1.770209 -0.621106 -1.382563  0.924840
7  0.823469 -0.815172  0.283333  1.072061
8  0.674455 -0.022174 -2.353393  1.240661
9 -0.006946 -1.963682 -0.887949  1.800675

### Grouping


In [66]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [67]:
df

A      B         C         D
0  foo    one  0.982202 -0.356411
1  bar    one -0.734893  2.324194
2  foo    two  0.841651  0.573649
3  bar  three  0.594950 -4.308362
4  foo    two -1.066912 -0.117060
5  bar    two -1.637283  0.214870
6  foo    one  0.525576  0.045471
7  foo  three  0.150546 -1.876742

In [68]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.734893  2.324194
    three  0.594950 -4.308362
    two   -1.637283  0.214870
foo one    1.507777 -0.310940
    three  0.150546 -1.876742
    two   -0.225261  0.456589

### Reshaping

In [69]:
# You can also stack or unstack levels

In [70]:
a = df.groupby(['A','B']).sum()

In [71]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -0.734893  0.594950 -1.637283  2.324194 -4.308362  0.214870
foo  0.753889  0.150546 -0.112630 -0.155470 -1.876742  0.228294

### Time Series


In [72]:
import pandas as pd
import numpy as np

In [73]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [74]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [75]:
ts

2014-01-01 00:00:00    446
2014-01-01 00:00:01    196
2014-01-01 00:00:02     25
2014-01-01 00:00:03    296
2014-01-01 00:00:04    446
2014-01-01 00:00:05     90
2014-01-01 00:00:06    385
2014-01-01 00:00:07    330
2014-01-01 00:00:08    289
2014-01-01 00:00:09    394
2014-01-01 00:00:10    347
2014-01-01 00:00:11    343
2014-01-01 00:00:12    425
2014-01-01 00:00:13    334
2014-01-01 00:00:14    193
2014-01-01 00:00:15     17
2014-01-01 00:00:16    166
2014-01-01 00:00:17    306
2014-01-01 00:00:18    178
2014-01-01 00:00:19    413
2014-01-01 00:00:20    213
2014-01-01 00:00:21     63
2014-01-01 00:00:22    400
2014-01-01 00:00:23    418
2014-01-01 00:00:24    438
2014-01-01 00:00:25    184
2014-01-01 00:00:26    146
2014-01-01 00:00:27    315
2014-01-01 00:00:28    401
2014-01-01 00:00:29     16
                      ... 
2014-01-01 00:01:10    313
2014-01-01 00:01:11    173
2014-01-01 00:01:12    131
2014-01-01 00:01:13    210
2014-01-01 00:01:14     65
2014-01-01 00:01:15    416
2

In [76]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    260.850
2014-01-01 00:01:00    252.075
Freq: T, dtype: float64

In [77]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-77-5c9240a56f62>, line 2)

### Plotting


In [78]:
ts.plot()

In [79]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [80]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [81]:
# Pandas plot function will print with labels as default

In [82]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas